/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const PeerStatus = IDL.Variant({
  'active' : IDL.Null,
  'joined' : IDL.Null,
  'called' : IDL.Null,
  'hangup' : IDL.Null,
});
export const Peer = IDL.Record({
  'status' : PeerStatus,
  'principal' : IDL.Principal,
  'joinedAt' : IDL.Opt(Time),
  'handle' : IDL.Text,
});
export const CallState = IDL.Variant({
  'end' : IDL.Null,
  'active' : IDL.Null,
  'pending' : IDL.Null,
});
export const CallSession = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'createdAt' : Time,
  'peer' : IDL.Opt(Peer),
  'updatedAt' : Time,
  'state' : CallState,
});
export const Contact = IDL.Record({
  'id' : Time,
  'name' : IDL.Text,
  'createdAt' : Time,
  'handle' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCallSession' : IDL.Func([], [CallSession], []),
  'createContact' : IDL.Func([IDL.Text, IDL.Text], [Contact], []),
  'deleteContact' : IDL.Func([Time], [], []),
  'endCallSession' : IDL.Func([IDL.Text], [], []),
  'getActiveCallSessions' : IDL.Func([], [IDL.Vec(CallSession)], ['query']),
  'getCallSession' : IDL.Func([IDL.Text], [CallSession], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinCallSession' : IDL.Func([IDL.Text, IDL.Text], [CallSession], []),
  'listContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const PeerStatus = IDL.Variant({
    'active' : IDL.Null,
    'joined' : IDL.Null,
    'called' : IDL.Null,
    'hangup' : IDL.Null,
  });
  const Peer = IDL.Record({
    'status' : PeerStatus,
    'principal' : IDL.Principal,
    'joinedAt' : IDL.Opt(Time),
    'handle' : IDL.Text,
  });
  const CallState = IDL.Variant({
    'end' : IDL.Null,
    'active' : IDL.Null,
    'pending' : IDL.Null,
  });
  const CallSession = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'createdAt' : Time,
    'peer' : IDL.Opt(Peer),
    'updatedAt' : Time,
    'state' : CallState,
  });
  const Contact = IDL.Record({
    'id' : Time,
    'name' : IDL.Text,
    'createdAt' : Time,
    'handle' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCallSession' : IDL.Func([], [CallSession], []),
    'createContact' : IDL.Func([IDL.Text, IDL.Text], [Contact], []),
    'deleteContact' : IDL.Func([Time], [], []),
    'endCallSession' : IDL.Func([IDL.Text], [], []),
    'getActiveCallSessions' : IDL.Func([], [IDL.Vec(CallSession)], ['query']),
    'getCallSession' : IDL.Func([IDL.Text], [CallSession], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinCallSession' : IDL.Func([IDL.Text, IDL.Text], [CallSession], []),
    'listContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };