/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CallSession {
  'id' : string,
  'creator' : Principal,
  'createdAt' : Time,
  'peer' : [] | [Peer],
  'updatedAt' : Time,
  'state' : CallState,
}
export type CallState = { 'end' : null } |
  { 'active' : null } |
  { 'pending' : null };
export interface Contact {
  'id' : Time,
  'name' : string,
  'createdAt' : Time,
  'handle' : string,
}
export interface Peer {
  'status' : PeerStatus,
  'principal' : Principal,
  'joinedAt' : [] | [Time],
  'handle' : string,
}
export type PeerStatus = { 'active' : null } |
  { 'joined' : null } |
  { 'called' : null } |
  { 'hangup' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCallSession' : ActorMethod<[], CallSession>,
  'createContact' : ActorMethod<[string, string], Contact>,
  'deleteContact' : ActorMethod<[Time], undefined>,
  'endCallSession' : ActorMethod<[string], undefined>,
  'getActiveCallSessions' : ActorMethod<[], Array<CallSession>>,
  'getCallSession' : ActorMethod<[string], CallSession>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinCallSession' : ActorMethod<[string, string], CallSession>,
  'listContacts' : ActorMethod<[], Array<Contact>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];